version: '2.1'

services:
    cassandra:
      image: cassandra:3.11
      hostname: cassandra
      ports:
          - '7000:7000'
          - '7001:7001'
          - '9042:9042'
          - '9160:9160'
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      networks:
          internal:

    elasticsearch:
      build: 
        context: ./Elasticsearch/
        dockerfile: Dockerfile
      image: vyeve/es
      ports:
        - "9200:9200"
        - "9300:9300"
      depends_on:
        - zookeeper
      networks:
          internal:

    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      networks:
          internal:

    kafka:
      image: ches/kafka
      ports:
        - "9092:9092"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=localhost
        - ZOOKEEPER_IP=zookeeper
        - ZOOKEEPER_CONNECTION_STRING=zookeeper:2181
        - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper 
      networks:
          internal:

networks:
  internal:
    driver: bridge

